export enum ProjectionEventType {
  IMAGE = 'IMAGE',
  IMAGE_VIEW_CHANGE = 'IMAGE_VIEW_CHANGE',
  COMBAT_UPDATE = 'COMBAT_UPDATE',
  COMBAT_VISIBILITY = 'COMBAT_VISIBILITY',
  COMBAT_ACTIVE_CHARACTER = 'COMBAT_ACTIVE_CHARACTER',
  TIMER = 'TIMER',
}
